+define+TARGET_SYNTHESIS
+define+TARGET_SPATZ
+define+SYNTHESIS_SRAM_BLACKBOX

+incdir+../../../../hw/common_cells/include
+incdir+../../../../hw/axi/include
+incdir+../../../../hw/snitch_cluster/hw/snitch/include
+incdir+../../../../hw/snitch_cluster/hw/snitch/include/cv_x_if
+incdir+../../../../hw/snitch_cluster/hw/reqrsp_interface/include
+incdir+../../../../hw/snitch_cluster/hw/tcdm_interface/include
+incdir+../../../../hw/snitch_cluster/hw/snitch_fp_ss/include
+incdir+../../../../hw/spatz/hw/ip/reqrsp_interface/include
+incdir+../../../../hw/spatz/hw/ip/tcdm_interface/include
+incdir+../../../../hw/obi/include
+incdir+../../../../hw/register_interface/include
+incdir+../../../../hw/axi_stream/include
+incdir+../../../../hw/idma/src/include

../../../../hw/rtl/cluster/synth/sram_blackboxes.sv

../../../../hw/axi/src/axi_pkg.sv
../../../../hw/obi/src/obi_pkg.sv
../../../../hw/spatz/hw/ip/reqrsp_interface/src/reqrsp_pkg.sv
../../../../hw/riscv-dbg/src/dm_pkg.sv
../../../../hw/fpnew/src/fpnew_pkg.sv

../../../../hw/common_cells/src/cf_math_pkg.sv
../../../../hw/common_cells/src/lzc.sv
../../../../hw/common_cells/src/onehot_to_bin.sv
../../../../hw/common_cells/src/popcount.sv
../../../../hw/common_cells/src/fifo_v3.sv
../../../../hw/common_cells/src/spill_register_flushable.sv
../../../../hw/common_cells/src/spill_register.sv
../../../../hw/common_cells/src/stream_fifo.sv
../../../../hw/common_cells/src/passthrough_stream_fifo.sv
../../../../hw/common_cells/src/fall_through_register.sv
../../../../hw/common_cells/src/stream_register.sv
../../../../hw/common_cells/src/id_queue.sv
../../../../hw/common_cells/src/rr_arb_tree.sv
../../../../hw/common_cells/src/delta_counter.sv
../../../../hw/common_cells/src/counter.sv
../../../../hw/common_cells/src/stream_fifo_optimal_wrap.sv
../../../../hw/common_cells/src/deprecated/rrarbiter.sv
../../../../hw/common_cells/src/deprecated/find_first_one.sv

../../../../hw/tech_cells/src/rtl/tc_clk.sv

../../../../hw/snitch_cluster/hw/snitch_ipu/src/snitch_multiplier.sv
../../../../hw/snitch_cluster/hw/snitch_ipu/src/snitch_serial_divider.sv
../../../../hw/snitch_cluster/hw/snitch_ipu/src/snitch_ipu.sv
../../../../hw/snitch_cluster/hw/snitch/src/snitch_pma_pkg.sv
../../../../hw/rtl/cluster/riscv_instr_npu.sv
../../../../hw/spatz/hw/ip/snitch/src/snitch_pkg.sv
../../../../hw/spatz/hw/ip/snitch/src/snitch_regfile_ff.sv
../../../../hw/spatz/hw/ip/snitch/src/snitch_lsu.sv
../../../../hw/spatz/hw/ip/snitch/src/snitch_l0_tlb.sv
../../../../hw/spatz/hw/ip/snitch/src/snitch.sv

../../../../hw/rtl/cluster/npu_cluster_pkg.sv
../../../../hw/rtl/cluster/obi_arbiter_2to1.sv
../../../../hw/rtl/cluster/obi_req_register_slice.sv
../../../../hw/rtl/cluster/obi_demux_1to4.sv
../../../../hw/rtl/cluster/obi_demux_1to5.sv
../../../../hw/rtl/cluster/obi_narrow_to_wide.sv
../../../../hw/rtl/cluster/axi_lite_to_obi.sv
../../../../hw/rtl/systolic/systolic_ctrl_regs.sv
../../../../hw/rtl/cluster/npu_interrupt_ctrl.sv
../../../../hw/rtl/cluster/npu_pmu.sv
../../../../hw/rtl/cluster/npu_cmd_ctrl.sv

../../../../hw/idma/src/idma_pkg.sv
../../../../hw/idma/src/backend/idma_axil_read.sv
../../../../hw/idma/src/backend/idma_axil_write.sv
../../../../hw/idma/src/backend/idma_axi_read.sv
../../../../hw/idma/src/backend/idma_axi_write.sv
../../../../hw/idma/src/backend/idma_axis_read.sv
../../../../hw/idma/src/backend/idma_axis_write.sv
../../../../hw/idma/src/backend/idma_channel_coupler.sv
../../../../hw/idma/src/backend/idma_dataflow_element.sv
../../../../hw/idma/src/backend/idma_error_handler.sv
../../../../hw/idma/src/backend/idma_init_read.sv
../../../../hw/idma/src/backend/idma_init_write.sv
../../../../hw/idma/src/backend/idma_legalizer_page_splitter.sv
../../../../hw/idma/src/backend/idma_legalizer_pow2_splitter.sv
../../../../hw/idma/src/backend/idma_obi_read.sv
../../../../hw/idma/src/backend/idma_obi_write.sv
../../../../hw/idma/src/backend/idma_tilelink_read.sv
../../../../hw/idma/src/backend/idma_tilelink_write.sv
../../../../hw/idma/src/midend/idma_nd_midend.sv
../../../../hw/idma/src/frontend/idma_transfer_id_gen.sv
../../../../hw/idma/target/rtl/idma_generated.sv

../../../../hw/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_arb.sv
../../../../hw/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_ext.sv
../../../../hw/register_interface/vendor/lowrisc_opentitan/src/prim_subreg.sv

../../../../hw/rtl/cluster/npu_pulp_idma_ctrl_mm.sv
../../../../hw/rtl/afu/afu_fifo_ff.sv
../../../../hw/rtl/afu/afu_frontend.sv
../../../../hw/rtl/afu/afu_backend.sv
../../../../hw/rtl/afu/afu_core.sv
../../../../hw/rtl/afu/afu.sv
../../../../hw/rtl/interconnect/tcdm_interconnect.sv
../../../../hw/rtl/systolic/requant_pipeline.sv
../../../../hw/rtl/systolic/conv_linebuf_stream_packer.sv
../../../../hw/rtl/systolic/systolic_controller.sv
../../../../hw/rtl/systolic/npu_systolic_array.sv
../../../../hw/rtl/cluster/snitch_core.sv

../../../../hw/spatz/hw/ip/spatz/src/reorder_buffer.sv
../../../../hw/spatz/hw/ip/spatz/src/rvv_pkg.sv
../../../../hw/spatz/hw/ip/spatz/src/vtl_pkg.sv
../../../../hw/rtl/spatz_overlay/generated/spatz_pkg.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_serdiv.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_decoder.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_simd_lane.sv
../../../../hw/spatz/hw/ip/spatz/src/vregfile.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_ipu.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_vfu.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_vlsu.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_doublebw_vlsu.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_vrf.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_vsldu.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz_controller.sv
../../../../hw/spatz/hw/ip/spatz/src/spatz.sv

../../../../hw/rtl/cluster/tcdm_to_obi_bridge.sv
../../../../hw/rtl/cluster/obi_snitch_if_adapter.sv
../../../../hw/rtl/cluster/npu_cluster.sv
