`default_nettype none

module systolic_ctrl_regs #(
    parameter int unsigned ADDR_WIDTH = 32,
    parameter int unsigned DATA_WIDTH = 32
)(
    input  logic clk_i,
    input  logic rst_ni,
    input  logic                      req_i,
    output logic                      gnt_o,
    input  logic [ADDR_WIDTH-1:0]     addr_i,
    input  logic                      we_i,
    input  logic [(DATA_WIDTH/8)-1:0] be_i,
    input  logic [DATA_WIDTH-1:0]     wdata_i,
    output logic                      rvalid_o,
    output logic [DATA_WIDTH-1:0]     rdata_o,
    output logic                      cfg_sys_start_o,
    output logic [31:0]               cfg_sys_weight_ptr_o,
    output logic [31:0]               cfg_sys_ifm_ptr_o,
    output logic [31:0]               cfg_sys_ofm_ptr_o,
    output logic [31:0]               cfg_sys_psum_ptr_o,
    output logic [31:0]               cfg_sys_dim_m_o,
    output logic                      cfg_sys_accum_en_o,
    output logic [31:0]               cfg_sys_ofm_row_stride_bytes_o,
    output logic [31:0]               cfg_sys_ofm_tile_cols_o,
    output logic [31:0]               cfg_sys_psum_row_stride_bytes_o,
    output logic                      cfg_requant_en_o,
    output logic [31:0][31:0]         cfg_requant_bias_o,
    output logic [31:0][31:0]         cfg_requant_multiplier_o,
    output logic [31:0][7:0]          cfg_requant_shift_o,
    output logic [31:0][31:0]         cfg_requant_zero_point_o,
    output logic [31:0]               cfg_requant_clamp_min_o,
    output logic [31:0]               cfg_requant_clamp_max_o,
    output logic                      cfg_linebuf_en_o,
    output logic                      cfg_linebuf_coalesce_o,
    output logic                      cfg_linebuf_pool_o,
    output logic                      cfg_linebuf_c32_fast_o,
    output logic                      cfg_linebuf_depthwise_o,
    output logic                      cfg_linebuf_c32_group_stationary_o,
    output logic [31:0]               cfg_linebuf_input_base_o,
    output logic [15:0]               cfg_linebuf_input_h_o,
    output logic [15:0]               cfg_linebuf_input_w_o,
    output logic [15:0]               cfg_linebuf_input_c_o,
    output logic [15:0]               cfg_linebuf_output_w_o,
    output logic [15:0]               cfg_linebuf_stride_h_o,
    output logic [15:0]               cfg_linebuf_stride_w_o,
    output logic [15:0]               cfg_linebuf_pad_h_o,
    output logic [15:0]               cfg_linebuf_pad_w_o,
    output logic [31:0]               cfg_linebuf_row_stride_bytes_o,
    output logic [31:0]               cfg_linebuf_pixel_stride_bytes_o,
    output logic [31:0]               cfg_linebuf_ow_step_bytes_o,
    output logic [31:0]               cfg_linebuf_oh_step_bytes_o,
    output logic [15:0]               cfg_linebuf_kernel_h_o,
    output logic [15:0]               cfg_linebuf_kernel_w_o,
    output logic [15:0]               cfg_linebuf_c_base_o,
    output logic [5:0]                cfg_linebuf_lane_base_o,
    output logic                      cfg_linebuf_kgen_o,
    output logic [31:0]               cfg_linebuf_k_tiles_o,
    output logic [15:0]               cfg_linebuf_k_seed_ic_o,
    output logic [7:0]                cfg_linebuf_k_seed_kw_o,
    output logic [7:0]                cfg_linebuf_k_seed_kh_o,
    output logic [31:0]               cfg_linebuf_spatial_m_o,
    output logic [5:0]                cfg_linebuf_block_valid_bytes_o,
    output logic [31:0]               cfg_linebuf_channel_addr_offset_o,
    output logic [31:0]               cfg_linebuf_coalesce_k_bytes_o,
    input  logic                      cfg_sys_done_i
);

    systolic_ctrl_regs_mapped i_mapped (
        .clk_i(clk_i), .rst_ni(rst_ni), .req_i(req_i), .gnt_o(gnt_o),
        .addr_i(addr_i), .we_i(we_i), .be_i(be_i), .wdata_i(wdata_i),
        .rvalid_o(rvalid_o), .rdata_o(rdata_o),
        .cfg_sys_start_o(cfg_sys_start_o),
        .cfg_sys_weight_ptr_o(cfg_sys_weight_ptr_o),
        .cfg_sys_ifm_ptr_o(cfg_sys_ifm_ptr_o),
        .cfg_sys_ofm_ptr_o(cfg_sys_ofm_ptr_o),
        .cfg_sys_psum_ptr_o(cfg_sys_psum_ptr_o),
        .cfg_sys_dim_m_o(cfg_sys_dim_m_o),
        .cfg_sys_accum_en_o(cfg_sys_accum_en_o),
        .cfg_sys_ofm_row_stride_bytes_o(cfg_sys_ofm_row_stride_bytes_o),
        .cfg_sys_ofm_tile_cols_o(cfg_sys_ofm_tile_cols_o),
        .cfg_sys_psum_row_stride_bytes_o(cfg_sys_psum_row_stride_bytes_o),
        .cfg_requant_en_o(cfg_requant_en_o),
        .cfg_requant_bias_o(cfg_requant_bias_o),
        .cfg_requant_multiplier_o(cfg_requant_multiplier_o),
        .cfg_requant_shift_o(cfg_requant_shift_o),
        .cfg_requant_zero_point_o(cfg_requant_zero_point_o),
        .cfg_requant_clamp_min_o(cfg_requant_clamp_min_o),
        .cfg_requant_clamp_max_o(cfg_requant_clamp_max_o),
        .cfg_linebuf_en_o(cfg_linebuf_en_o),
        .cfg_linebuf_coalesce_o(cfg_linebuf_coalesce_o),
        .cfg_linebuf_pool_o(cfg_linebuf_pool_o),
        .cfg_linebuf_c32_fast_o(cfg_linebuf_c32_fast_o),
        .cfg_linebuf_depthwise_o(cfg_linebuf_depthwise_o),
        .cfg_linebuf_c32_group_stationary_o(cfg_linebuf_c32_group_stationary_o),
        .cfg_linebuf_input_base_o(cfg_linebuf_input_base_o),
        .cfg_linebuf_input_h_o(cfg_linebuf_input_h_o),
        .cfg_linebuf_input_w_o(cfg_linebuf_input_w_o),
        .cfg_linebuf_input_c_o(cfg_linebuf_input_c_o),
        .cfg_linebuf_output_w_o(cfg_linebuf_output_w_o),
        .cfg_linebuf_stride_h_o(cfg_linebuf_stride_h_o),
        .cfg_linebuf_stride_w_o(cfg_linebuf_stride_w_o),
        .cfg_linebuf_pad_h_o(cfg_linebuf_pad_h_o),
        .cfg_linebuf_pad_w_o(cfg_linebuf_pad_w_o),
        .cfg_linebuf_row_stride_bytes_o(cfg_linebuf_row_stride_bytes_o),
        .cfg_linebuf_pixel_stride_bytes_o(cfg_linebuf_pixel_stride_bytes_o),
        .cfg_linebuf_ow_step_bytes_o(cfg_linebuf_ow_step_bytes_o),
        .cfg_linebuf_oh_step_bytes_o(cfg_linebuf_oh_step_bytes_o),
        .cfg_linebuf_kernel_h_o(cfg_linebuf_kernel_h_o),
        .cfg_linebuf_kernel_w_o(cfg_linebuf_kernel_w_o),
        .cfg_linebuf_c_base_o(cfg_linebuf_c_base_o),
        .cfg_linebuf_lane_base_o(cfg_linebuf_lane_base_o),
        .cfg_linebuf_kgen_o(cfg_linebuf_kgen_o),
        .cfg_linebuf_k_tiles_o(cfg_linebuf_k_tiles_o),
        .cfg_linebuf_k_seed_ic_o(cfg_linebuf_k_seed_ic_o),
        .cfg_linebuf_k_seed_kw_o(cfg_linebuf_k_seed_kw_o),
        .cfg_linebuf_k_seed_kh_o(cfg_linebuf_k_seed_kh_o),
        .cfg_linebuf_spatial_m_o(cfg_linebuf_spatial_m_o),
        .cfg_linebuf_block_valid_bytes_o(cfg_linebuf_block_valid_bytes_o),
        .cfg_linebuf_channel_addr_offset_o(cfg_linebuf_channel_addr_offset_o),
        .cfg_linebuf_coalesce_k_bytes_o(cfg_linebuf_coalesce_k_bytes_o),
        .cfg_sys_done_i(cfg_sys_done_i)
    );

endmodule

`default_nettype wire
